---
modules-search: [ local ]
branding: hyperos

prompt-install: true
dont-chroot: false
oem-setup: false

# Execution sequence
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary

  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - initramfs
      - grubcfg
      - bootloader
      - shellprocess
      - umount

# Global behavior
disable-cancel: false
disable-cancel-during-exec: true

# Safety + logging
debug: false
