---
modules-search: [ local ]
branding: hyperos
prompt-install: true
dont-chroot: false
oem-setup: false

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - initramfscfg
      - grubcfg
      - bootloader
      - shellprocess
      - umount
