---
dontChroot: false
timeout: 1200
script:
  - command: "apt-get -y purge live-boot live-config || true"
  - command: "rm -f /etc/systemd/system/check-live-persistence.service /usr/local/sbin/check-live-persistence"
  - command: "systemctl enable NetworkManager.service lightdm.service"
  - command: "update-initramfs -u"
