---
unpack:
  - source: /run/live/medium/live/filesystem.squashfs
    sourcefs: squashfs
    destination: /

  - source: /lib/live/mount/medium/live/filesystem.squashfs
    sourcefs: squashfs
    destination: /

# Fallback safety
overwrite: true
preservePermissions: true
