PROFILE_NAME="Elden Ring"
PROCESS_MATCH="eldenring.exe|start_protected_game.exe"
PROTON_VERSION="GE-Proton9"
CPU_GOVERNOR="performance"
IO_SCHEDULER="bfq"
ENABLE_GAMEMODE=1
MANGOHUD=1
DXVK_HUD=0
VKD3D_CONFIG="dxr11"
WINE_ESYNC=1
WINE_FSYNC=1
NVIDIA_OFFLOAD=0
