# Hyper OS game profile: Lutris default
PROFILE_NAME="Lutris Default"
PROCESS_MATCH="lutris|wine|wine64"
CPU_GOVERNOR="performance"
IO_SCHEDULER="bfq"
ENABLE_GAMEMODE=1
NICE_LEVEL=-6
IRQBALANCE_ONESHOT=1
ENV_VARS="MANGOHUD=1 DXVK_HUD=0 WINEESYNC=1 WINEFSYNC=1"
NVIDIA_OFFLOAD=1
